//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expense_Client_App.ExpenseServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Expense", Namespace="http://schemas.datacontract.org/2004/07/ExpenseTracker_WCF")]
    [System.SerializableAttribute()]
    public partial class Expense : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExpenseIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExpenseId {
            get {
                return this.ExpenseIdField;
            }
            set {
                if ((this.ExpenseIdField.Equals(value) != true)) {
                    this.ExpenseIdField = value;
                    this.RaisePropertyChanged("ExpenseId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ExpenseServiceReference.IExpenseService")]
    public interface IExpenseService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExpenseService/GetExpenses", ReplyAction="http://tempuri.org/IExpenseService/GetExpensesResponse")]
        Expense_Client_App.ExpenseServiceReference.Expense[] GetExpenses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExpenseService/GetExpenses", ReplyAction="http://tempuri.org/IExpenseService/GetExpensesResponse")]
        System.Threading.Tasks.Task<Expense_Client_App.ExpenseServiceReference.Expense[]> GetExpensesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExpenseService/AddExpense", ReplyAction="http://tempuri.org/IExpenseService/AddExpenseResponse")]
        void AddExpense(Expense_Client_App.ExpenseServiceReference.Expense expense);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExpenseService/AddExpense", ReplyAction="http://tempuri.org/IExpenseService/AddExpenseResponse")]
        System.Threading.Tasks.Task AddExpenseAsync(Expense_Client_App.ExpenseServiceReference.Expense expense);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExpenseService/UpdateExpense", ReplyAction="http://tempuri.org/IExpenseService/UpdateExpenseResponse")]
        void UpdateExpense(Expense_Client_App.ExpenseServiceReference.Expense expense);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExpenseService/UpdateExpense", ReplyAction="http://tempuri.org/IExpenseService/UpdateExpenseResponse")]
        System.Threading.Tasks.Task UpdateExpenseAsync(Expense_Client_App.ExpenseServiceReference.Expense expense);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExpenseService/DeleteExpense", ReplyAction="http://tempuri.org/IExpenseService/DeleteExpenseResponse")]
        void DeleteExpense(int expenseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExpenseService/DeleteExpense", ReplyAction="http://tempuri.org/IExpenseService/DeleteExpenseResponse")]
        System.Threading.Tasks.Task DeleteExpenseAsync(int expenseId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IExpenseServiceChannel : Expense_Client_App.ExpenseServiceReference.IExpenseService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExpenseServiceClient : System.ServiceModel.ClientBase<Expense_Client_App.ExpenseServiceReference.IExpenseService>, Expense_Client_App.ExpenseServiceReference.IExpenseService {
        
        public ExpenseServiceClient() {
        }
        
        public ExpenseServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExpenseServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExpenseServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExpenseServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Expense_Client_App.ExpenseServiceReference.Expense[] GetExpenses() {
            return base.Channel.GetExpenses();
        }
        
        public System.Threading.Tasks.Task<Expense_Client_App.ExpenseServiceReference.Expense[]> GetExpensesAsync() {
            return base.Channel.GetExpensesAsync();
        }
        
        public void AddExpense(Expense_Client_App.ExpenseServiceReference.Expense expense) {
            base.Channel.AddExpense(expense);
        }
        
        public System.Threading.Tasks.Task AddExpenseAsync(Expense_Client_App.ExpenseServiceReference.Expense expense) {
            return base.Channel.AddExpenseAsync(expense);
        }
        
        public void UpdateExpense(Expense_Client_App.ExpenseServiceReference.Expense expense) {
            base.Channel.UpdateExpense(expense);
        }
        
        public System.Threading.Tasks.Task UpdateExpenseAsync(Expense_Client_App.ExpenseServiceReference.Expense expense) {
            return base.Channel.UpdateExpenseAsync(expense);
        }
        
        public void DeleteExpense(int expenseId) {
            base.Channel.DeleteExpense(expenseId);
        }
        
        public System.Threading.Tasks.Task DeleteExpenseAsync(int expenseId) {
            return base.Channel.DeleteExpenseAsync(expenseId);
        }
    }
}
